[package]
name = "reing"
version = "0.1.0"
authors = ["Yusuke Sangenya <longinus.eva@gmail.com>"]

[dependencies]
dotenv = "0.11.0"
chrono = { version = "0.4.2", features = ["serde"] }
uuid = { version = "0.6", features = ["v4"] }

rocket = "0.3.15"
rocket_codegen = "0.3.15"
rocket_contrib = { version = "0.3.15", features = ["handlebars_templates", "tera_templates"] }
base64 = "0.9.1"
serde = "1.0.53"
serde_derive = "1.0.53"

egg-mode = "0.12.0"
tokio-core = "0.1.17"

diesel = { version = "1.0.0", features = ["postgres", "chrono"] }
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"

image = "0.19.0"
imageproc = "0.15.0"
rusttype = "0.5.2"

lettre = { git = "https://github.com/lettre/lettre", rev = "fc91bb6ee8f9a28b818e98598af0a83a0dbb41d3" }
lettre_email = { git = "https://github.com/lettre/lettre", rev = "fc91bb6ee8f9a28b818e98598af0a83a0dbb41d3" }
