[package]
name = "reing"
version = "0.1.0"
authors = ["Yusuke Sangenya <longinus.eva@gmail.com>"]

[dependencies]
rocket = "0.3.10"
rocket_codegen = "0.3.10"
pinto = "0.6"
dotenv = "0.11.0"
r2d2 = "0.8.2"
r2d2_postgres = "0.14.0"
postgres = { version = "0.15.2", features = ["with-chrono"] }
chrono = "0.4.2"